### ISSUE TITLE
We need to workaround broken mqtt and mqtt-packet versions

### ISSUE THREAD

**Issue by cstim** [bheisen/vrpc#17]
**Problem**
The current dependency of npm package `mqtt` 4.2.4 contains a problem that will occasionally break when receiving mqtt messages longer than 255 bytes, showing a "Error: Invalid length" exception.  The actual issue is contained in the sub-dependency `mqtt-packet`, where version 6.6.0 is affected. 

**Details**
Of `mqtt-packet`, the previous version 6.5.0 and lower are not affected, 6.6.0 is affected, and any version higher (i.e. 6.6.1 or higher) will not be affected anymore. See issue https://github.com/mqttjs/mqtt-packet/issues/95 and resolving PR https://github.com/mqttjs/mqtt-packet/pull/96

Hence, `mqtt` 4.2.2 and lower is not affected, but 4.2.3 through 4.2.6 are affected. There is not yet a version available which is not affected anymore.

**Course of action**
Please downgrade to mqtt 4.2.2. Once a newer mqtt with the resolution is available, this needs to be updated again.

**Comment by bheisen** [comment]
Thanks for reporting this issue. Unfortunately, I however believe that your proposed fix won't work as the `package.json` file of `mqtt` uses:
```
"mqtt-packet": "^6.3.2"
```
and hence will still pull in the broken 6.6.0 version. I will try to find another way to fix the described issue.

**Comment by bheisen** [comment]
Ok, a solution was found (explicit downgrade of sub-dependency `mqtt-packet`) and is pushed to master. A bug-fix release will be triggered once CI runs show green.

**Comment by cstim** [comment]
hm.... no, I don't think this achieves the intended result. In client project, after removing node_modules and letting `npm install` run, I now get:
```
node_modules/mqtt-packet/package.json:  "version": "6.6.0"
node_modules/vrpc/node_modules/mqtt-packet/package.json:  "version": "6.5.0"
node_modules/vrpc/node_modules/mqtt/node_modules/mqtt-packet/package.json:  "version": "6.6.0"
```
So doesn't this mean that the actual mqtt implementation will still use bug-affected 6.6.0, as requested by their package.json?

**Comment by cstim** [comment]
Ok, this version is fine for now.

In a downstream application, I also need to modify package-lock.json to downgrade mqtt-package. Then it works.

**Comment by cstim** [comment]
In the meantime, mqtt-package 6.7.0 was released that contains the bugfix. So vrpc-2.2.3 is no longer urgently needed. You might consider updating your mqtt-package dependency to 6.7.0, though. Thanks for the quick reaction.
