### ISSUE TITLE
static remote calls don't support promises

### ISSUE THREAD

**Issue by psorowka** [bheisen/vrpc#2]
**Environment:**
- vrpc 2.0.1
- NodeJS (VrpcRemote) -> MQTT -> NodeJS (VrpcAdapter)

**Minimal sample**

```
# on the remote site
class Test {
  static async myFunc () {
    return 'foobar'
  }
}

VrpcAdapter.register(Test)
...
```

```
# on the local site
const result = await vrpcRemote.callStatic({
  className: 'Test',
  functionName: 'myFunc'
})

console.log(result)
```

This will not output `foobar` (as expected), but a string similar to `__p__myFunc-0` which is obviously the internal call id of the promise.

Reading through the code it appears that promise handling for static functions is just not implemented yet. The same works perfectly for regular instance member functions.

**Comment by bheisen** [comment]
Fixed by: 1db4671dc3f77574b731eebc5f3e1be1bad801ca
