### ISSUE TITLE
Account registration URL does not work

### ISSUE THREAD

**Issue by cstim** [bheisen/vrpc#6]
When following the instructions for testing the examples, one is asked to register an account at https://vrpc.io/app , but the page is empty: "here is nothing, not even a 404"
It's not Bielefeld, but hey...

**Comment by cstim** [comment]
Some documents in the examples folder still contain links to https://vrpc.io/web/download which obviously has changed, too. See e.g.
https://github.com/bheisen/vrpc/blob/master/docs/examples/CppAgentLinuxExample1.md

**Comment by bheisen** [comment]
Thanks for the correct bug report. All such issues should be fixed.
